# Model Architecture (Only if weights are specified)
# KerasJson: parkingModels/model2.json
# Model weights or whole model in .h5 format
KerasH5: trainedModelKerasFormat/model.h5
InputData: simFiles/inputs.npy
OutputPredictions: simFiles/outputs.npy
OutputDir: my-hls-test
ProjectName: myproject
XilinxPart: xc7z020clg400-1
# In ns
ClockPeriod: 10
Backend: Vivado

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_uint<32>
    ReuseFactor: 3
    Strategy: Latency
  LayerType:
    Dense:
      Precision: 
        weight: ap_fixed<64,32>
        bias: ap_fixed<64,32>
        result: ap_fixed<64,32>
    Relu:
      Precision: ap_fixed<64,32>

       
